# fly.toml app configuration file generated for realstate on 2025-08-10T15:30:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "realstate-app"
primary_region = "nrt"

[build]

[env]
  FLASK_APP = "app.py"
  FLASK_ENV = "production"
  PORT = "5001"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "realstate_data"
  destination = "/app/collected_data"
